# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DebugBuild

on:
  push:
    branches:
      - master

env:
  # リポジトリのルートディレクトリを起点としたソリューションファイルのパス
  SOLUTION_FILE_PATH: GE3_GameEngine.sln
  # Visual Studio の構成(DEBUG / Release)
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
