# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ReleaseBuild

on:
  push:
    branches:
      - master

env:
  # リポジトリのルートディレクトリを起点としたソリューションファイルのパス
  SOLUTION_FILE_PATH: Unnamed.sln
  # Visual Studio の構成(DEBUG / Release)
  CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup premake
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta7"
          path: ./

      - name: Show files in the current directory
        run: ls ./

      - name: Compile my project
        run: premake5 vs2022

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
